"""Prompt templates for agents."""

from .trip_prompts import (
    ALL_AGENT_PROMPTS,
    ATTRACTION_AGENT_PROMPT,
    FLIGHT_AGENT_PROMPT,
    HOTEL_AGENT_PROMPT,
    PLANNER_AGENT_PROMPT,
    PLANNER_EXTRA_SECTIONS,
    REQUIRED_PROMPT_SECTIONS,
    VISA_AGENT_PROMPT,
    WEATHER_AGENT_PROMPT,
)

__all__ = [
    "ALL_AGENT_PROMPTS",
    "ATTRACTION_AGENT_PROMPT",
    "FLIGHT_AGENT_PROMPT",
    "HOTEL_AGENT_PROMPT",
    "PLANNER_AGENT_PROMPT",
    "PLANNER_EXTRA_SECTIONS",
    "REQUIRED_PROMPT_SECTIONS",
    "VISA_AGENT_PROMPT",
    "WEATHER_AGENT_PROMPT",
]
